### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by aitkhsh** [aitkhsh/knitcommu#43]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

■1週間辺りの開発に向けられる時間
- 1週間あたり：50時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/aitkhsh/projects/1

■MVPリリースまで
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] プロフィール投稿機能
- [ ] プロフィール画像アップロード機能
- [ ] コメント機能
- [ ] 動的OGPのXシェア機能
- [ ] アイテム獲得機能
- [ ] 検索機能
- [ ] タグ機能
- [ ] タグ絞り機能
- [ ] Google Analyticsの導入

■MVP後
- [ ] アイテム交換
- [ ] ページネーション
- [ ] タグの自動生成
- [ ] レコメンド機能
- [ ] ユーザーの退会機能
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] 使い方ガイドの作成
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] 独自ドメイン・SSL
- [ ] SEO
- [ ] RSpec（モデルテスト・システムテスト）

■MVPレビュー依頼予定日
予定日：2024年 10月 20日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
